import React, { useEffect, useRef, useState } from 'react';
import mermaid from 'mermaid';

mermaid.initialize({
    startOnLoad: false,
    theme: 'default',
    securityLevel: 'loose',
});

const MermaidViewer = ({ chartSyntax }) => {
    const containerRef = useRef(null);
    const [error, setError] = useState(false);

    useEffect(() => {
        if (!chartSyntax || !containerRef.current) return;

        const renderChart = async () => {
            try {
                setError(false);
                containerRef.current.innerHTML = ''; // Clear previous
                
                const id = `mermaid-${Math.random().toString(36).substring(2, 10)}`;
                const renderResult = await mermaid.render(id, chartSyntax);
                
                // Extract SVG whether Mermaid returns a string (v9) or an object (v10+)
                const svgText = typeof renderResult === 'string' ? renderResult : renderResult.svg;
                
                if (svgText) {
                     containerRef.current.innerHTML = svgText;
                } else {
                     throw new Error("Empty SVG generated");
                }
            } catch (err) {
                console.error("Mermaid parsing error:", err);
                setError(true);
            }
        };

        renderChart();
    }, [chartSyntax]);

    if (error) {
        return (
            <div className="p-4 bg-red-50 text-red-600 rounded-lg border border-red-200">
                <p className="font-bold">Invalid Map Syntax Generated by AI.</p>
                <p className="text-sm mb-2">Please try generating again.</p>
                <pre className="text-xs bg-white p-2 rounded overflow-x-auto border border-red-100">{chartSyntax}</pre>
            </div>
        );
    }

    return (
        <div 
            ref={containerRef} 
            className="w-full overflow-x-auto bg-white rounded-lg p-6 flex justify-center items-center min-h-[300px]"
        />
    );
};

export default MermaidViewer;